#requires -Version 5.1
<#
.SYNOPSIS
    Base64-packs alleaves_setup.ps1 into the single double-clickable
    Install-Alleaves.bat deliverable.

.DESCRIPTION
    - Reads alleaves_setup.ps1 as RAW BYTES (guarantees a byte-identical decode
      on the client, regardless of BOM / line endings).
    - Base64-encodes and chunks into <=4000-char lines (under cmd's ~8191 line
      limit).
    - Emits a .bat that: elevates ONCE (whoami elevated-integrity SID probe -
      High OR SYSTEM),
      transports the base64 via a TEMP FILE (not an env var - a single cmd var
      caps at ~8191 chars and would silently truncate the ~40 KB blob), decodes
      it with 64-bit PowerShell (Sysnative), runs the .ps1 synchronously in the
      elevated console, and propagates the exit code.
    - Self-verifies by re-reading the .bat IT JUST WROTE: pulls the base64 back
      out of the emitted echo lines, decodes it, and confirms byte-length AND
      SHA256 identity to the source. Verifying the in-memory chunks instead
      would be circular and could never catch a transport-emission defect.
#>

[CmdletBinding()]
param(
    [string]$Source,
    [string]$OutBat
)

$ScriptDir = $PSScriptRoot
if (-not $Source) { $Source = Join-Path $ScriptDir 'alleaves_setup.ps1' }
if (-not $OutBat) { $OutBat = Join-Path $ScriptDir 'Install-Alleaves.bat' }

# -LiteralPath on both this and the Get-FileHash below: -Path treats [ ] as wildcards, so a
# checkout under a bracketed directory throws "Source not found" on a file that is right there.
if (-not (Test-Path -LiteralPath $Source)) { throw "Source not found: $Source" }

$srcBytes = [IO.File]::ReadAllBytes($Source)
$b64      = [Convert]::ToBase64String($srcBytes)
$chunks   = [regex]::Matches($b64, '.{1,4000}') | ForEach-Object { $_.Value }
Write-Host "Source:  $Source ($($srcBytes.Length) bytes)"
Write-Host "Base64:  $($b64.Length) chars in $($chunks.Count) chunk line(s)"

$b64File = 'alleaves_b64.txt'
$psFile  = 'alleaves_setup.ps1'

# --- Build the .bat -------------------------------------------------------
$L = New-Object System.Collections.Generic.List[string]
$L.Add('@echo off')
$L.Add('setlocal enableextensions')
$L.Add('REM ===================================================================')
$L.Add('REM  Install-Alleaves.bat - GENERATED by build-bat.ps1. Do not edit by')
$L.Add('REM  hand; edit alleaves_setup.ps1 and rebuild.')
$L.Add('REM  Double-click = install.  "-Uninstall" = reverse.  "-DryRun" = test.')
$L.Add('REM ===================================================================')
$L.Add('')
$L.Add('REM --- Single elevation owner: probe elevated-integrity SID, relaunch once.')
$L.Add('REM  BOTH SIDs: 12288 is High, 16384 is SYSTEM - strictly higher, and the exact RMM')
$L.Add('REM  case the .ps1 anticipates with its "service-account" precheck verdict. Matching')
$L.Add('REM  High alone made a SYSTEM-dispatched run fail the probe and RunAs itself; SYSTEM''s')
$L.Add('REM  token is already elevated so no UAC gate stops it, and the child failed the same')
$L.Add('REM  probe and spawned another - an unbounded, mutually-waiting fork chain, with the')
$L.Add('REM  exit-8 verdict for that account never reaching the operator.')
$L.Add('REM  FULL PATH, never a bare "whoami": the name is resolved through PATH, and a')
$L.Add('REM  git-bash / MSYS / Cygwin shell puts its own GNU whoami first - which rejects')
$L.Add('REM  /groups, exits 1, and reads as "not elevated". The relaunch then inherits the')
$L.Add('REM  same PATH, the child fails identically, and it forks unboundedly: one UAC')
$L.Add('REM  prompt per iteration, hundreds deep. Same fork chain as the SYSTEM case above,')
$L.Add('REM  reached through a shadowed command name instead of an already-elevated token.')
$L.Add('set "WHOAMI=%SystemRoot%\System32\whoami.exe"')
$L.Add('if not exist "%WHOAMI%" goto :probefail')
$L.Add('"%WHOAMI%" /groups | findstr /c:"S-1-16-12288" /c:"S-1-16-16384" >nul 2>&1')
$L.Add('if not errorlevel 1 goto :elevated')
$L.Add('REM  Second probe = the fork guard. A WORKING whoami always prints a mandatory-label')
$L.Add('REM  SID (S-1-16-*); no label at all means the probe is broken, not that the token is')
$L.Add('REM  unelevated. Relaunching on a broken probe is exactly what forks, so abort instead.')
$L.Add('"%WHOAMI%" /groups | findstr /c:"S-1-16-" >nul 2>&1')
$L.Add('if errorlevel 1 goto :probefail')
$L.Add('echo Requesting administrator elevation...')
$L.Add('REM F21: -Wait -PassThru so the non-elevated launcher waits for the elevated child')
$L.Add('REM and propagates its real exit code. The "exit /b %ERRORLEVEL%" below MUST stay')
$L.Add('REM OUTSIDE any ( ) block: inside a parenthesized block cmd freezes %ERRORLEVEL% at')
$L.Add('REM parse time to the find result (=1), which would report a successful install as')
$L.Add('REM failure. This relaunch is INTERACTIVE-only: ALLEAVES_NOPAUSE is not forwarded')
$L.Add('REM across the UAC boundary, so RMM/unattended MUST invoke the .bat already-elevated.')
$L.Add('if "%~1"=="" (')
$L.Add('  powershell -NoProfile -Command "exit (Start-Process -FilePath ''%~f0'' -Verb RunAs -Wait -PassThru).ExitCode"')
$L.Add(') else (')
$L.Add('  powershell -NoProfile -Command "exit (Start-Process -FilePath ''%~f0'' -ArgumentList ''%*'' -Verb RunAs -Wait -PassThru).ExitCode"')
$L.Add(')')
$L.Add('exit /b %ERRORLEVEL%')
$L.Add('')
$L.Add(':probefail')
$L.Add('echo [FAIL] Cannot determine this token''s integrity level - refusing to relaunch.')
$L.Add('echo        %SystemRoot%\System32\whoami.exe did not report a mandatory-label SID.')
$L.Add('echo        Run Install-Alleaves.bat from cmd.exe or Explorer, not from a bash/MSYS')
$L.Add('echo        shell - relaunching on an unreadable probe forks without bound.')
$L.Add('exit /b 3')
$L.Add('')
$L.Add(':elevated')
$L.Add('')
$L.Add('REM --- Record requested mode so the .ps1 can refuse a dropped -Uninstall.')
$L.Add('set "ALLEAVES_REQUESTED_MODE=install"')
$L.Add('echo %*| find /i "-uninstall" >nul 2>&1 && set "ALLEAVES_REQUESTED_MODE=uninstall"')
$L.Add('echo Mode: %ALLEAVES_REQUESTED_MODE%')
$L.Add('')
$L.Add('REM --- Force 64-bit PowerShell (Sysnative when launched from a 32-bit shell).')
$L.Add('set "PS=%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe"')
$L.Add('if exist "%SystemRoot%\Sysnative\WindowsPowerShell\v1.0\powershell.exe" set "PS=%SystemRoot%\Sysnative\WindowsPowerShell\v1.0\powershell.exe"')
$L.Add('')
$L.Add("REM --- Transport base64 via a TEMP FILE (cmd env vars truncate at ~8191).")
$L.Add("if exist `"%TEMP%\$b64File`" del /f /q `"%TEMP%\$b64File`"")
# Pre-delete the DECODED script too. The decode's exit code is never checked and the only
# guard below is "if not exist", so a run killed between the decode and the trailing del
# leaves the PREVIOUS build's .ps1 in %TEMP% - and a later run whose decode fails then runs
# THAT against a terminal, with its exit code attributed to the new build.
$L.Add("if exist `"%TEMP%\$psFile`" del /f /q `"%TEMP%\$psFile`"")
# Redirection FIRST, command second: ">>file echo <chunk>" rather than
# "echo <chunk>>>file". cmd reads a digit sitting just before a redirection
# operator as a HANDLE (the classic "echo done 2>log" trap), and 11 of the ~102
# base64 chunks currently end in 0-9. Measured on Win11 26200 the glued form is
# in fact safe - cmd only takes the digit as a handle when a delimiter precedes
# it, and the base64 alphabet (A-Za-z0-9+/=) never puts a space before that last
# character - so this is belt-and-braces, not a live bug. It costs nothing, it
# removes the need for the next reader to re-derive that parsing subtlety, and
# nothing else in the alphabet is a cmd metacharacter (+ / = are all inert here).
foreach ($c in $chunks) {
    $L.Add(">>`"%TEMP%\$b64File`" echo $c")
}
$L.Add('')
$L.Add('REM --- Decode the base64 file back to the original .ps1 bytes.')
$L.Add("`"%PS%`" -NoProfile -Command `"[IO.File]::WriteAllBytes(`$env:TEMP+'\$psFile',[Convert]::FromBase64String([IO.File]::ReadAllText(`$env:TEMP+'\$b64File')))`"")
$L.Add("if not exist `"%TEMP%\$psFile`" (")
$L.Add('  echo FATAL: decode failed - PowerShell could not write the script.')
$L.Add("  del /f /q `"%TEMP%\$b64File`" >nul 2>&1")
$L.Add('  pause')
$L.Add('  exit /b 9')
$L.Add(')')
$L.Add('')
$L.Add('REM --- Run synchronously in this elevated console; propagate exit code.')
$L.Add("REM  Note: -ExecutionPolicy Bypass loses to an AllSigned/Restricted GPO;")
$L.Add('REM  if that bites on a managed fleet, switch to piping via -EncodedCommand.')
$L.Add('REM  F25: %* forwards all args in one expansion. QUOTE any -SkipPrograms regex')
$L.Add('REM  containing cmd metacharacters (| ^ & < >), e.g. -SkipPrograms "Chrome|NiceLabel"')
$L.Add('REM  - unquoted metacharacters are interpreted by cmd and get mangled. Callers')
$L.Add('REM  needing exotic regexes should invoke alleaves_setup.ps1 directly.')
$L.Add("`"%PS%`" -NoProfile -ExecutionPolicy Bypass -File `"%TEMP%\$psFile`" %*")
$L.Add('set "RC=%ERRORLEVEL%"')
$L.Add('')
$L.Add('REM --- Temp hygiene + surface result for RMM/monitoring.')
$L.Add("del /f /q `"%TEMP%\$psFile`" >nul 2>&1")
$L.Add("del /f /q `"%TEMP%\$b64File`" >nul 2>&1")
$L.Add('echo.')
$L.Add('echo Alleaves setup exit code: %RC%')
$L.Add('REM  Skip the pause for unattended/RMM runs: set ALLEAVES_NOPAUSE=1.')
$L.Add('if not defined ALLEAVES_NOPAUSE pause')
$L.Add('exit /b %RC%')

# Write as ASCII (no BOM - a BOM on line 1 breaks @echo off) with CRLF.
$content = ($L -join "`r`n") + "`r`n"
[IO.File]::WriteAllText($OutBat, $content, (New-Object System.Text.ASCIIEncoding))
Write-Host "Wrote:   $OutBat ($((Get-Item $OutBat).Length) bytes)"

# --- Self-verify: decode the base64 back OUT OF THE WRITTEN .bat -----------
# Deliberately NOT $chunks: that variable IS the source by construction, so
# comparing it to the source can only ever pass. It cannot see a defect
# introduced while emitting the transport (a mangled echo line, a character the
# cmd parser eats, a dropped or reordered line) - which is the only kind of
# corruption this build step can actually cause. So re-read the file we just
# wrote and decode what the client's cmd will really append.
# [Convert]::FromBase64String ignores whitespace, which is what lets this join
# the lines back with no separator handling - and is also why the client's
# ReadAllText of the CRLF-separated temp file decodes cleanly.
$prefix  = ">>`"%TEMP%\$b64File`" echo "
$emitted = [IO.File]::ReadAllLines($OutBat) |
           Where-Object   { $_.StartsWith($prefix, [StringComparison]::Ordinal) } |
           ForEach-Object { $_.Substring($prefix.Length) }
$decoded = [byte[]]@()
# Corrupt base64 THROWS; catch it so a bad build still reports through the
# RESULT line / exit 1 contract below instead of dying with a stack trace.
try   { $decoded = [Convert]::FromBase64String(($emitted -join '')) }
catch { Write-Host "  decode of emitted lines FAILED: $($_.Exception.Message)" -ForegroundColor Red }
$srcHash = (Get-FileHash -LiteralPath $Source -Algorithm SHA256).Hash
$tmp = [IO.Path]::GetTempFileName()
[IO.File]::WriteAllBytes($tmp, $decoded)
$decHash = (Get-FileHash -Path $tmp -Algorithm SHA256).Hash
Remove-Item $tmp -Force -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "=== Self-verification ==="
Write-Host "  source bytes : $($srcBytes.Length)"
Write-Host "  decoded bytes: $($decoded.Length)"
Write-Host "  source SHA256: $srcHash"
Write-Host "  decode SHA256: $decHash"
if ($decoded.Length -eq $srcBytes.Length -and $decHash -eq $srcHash) {
    Write-Host "  RESULT: byte-length AND SHA256 identical - OK" -ForegroundColor Green
    exit 0
} else {
    Write-Host "  RESULT: MISMATCH - build is corrupt" -ForegroundColor Red
    # The .bat IS the whole deliverable, so a corrupt one must not keep the shipping name:
    # exit 1 alone left a plausible, double-clickable Install-Alleaves.bat in the repo root,
    # one `git add -A` from being shipped to a terminal.
    Move-Item -LiteralPath $OutBat -Destination "$OutBat.corrupt" -Force
    Write-Host "  moved aside: $OutBat.corrupt" -ForegroundColor Red
    exit 1
}
