#requires -Version 5.1
<#
.SYNOPSIS
    Base64-packs alleaves_setup.ps1 into the single double-clickable
    Install-Alleaves.bat deliverable, then self-verifies the result.

.DESCRIPTION
    Run this after EVERY edit to alleaves_setup.ps1. Never hand-edit the .bat.
    A failed self-verify renames the output to .bat.corrupt and exits 1.

    How it works and why each part is the way it is: docs/BUILD-BAT.md
    A dev run needs no pack at all: docs/BUILD-BAT.md#dev
#>

[CmdletBinding()]
param(
    [string]$Source,
    [string]$OutBat
)

$ScriptDir = $PSScriptRoot
if (-not $Source) { $Source = Join-Path $ScriptDir 'alleaves_setup.ps1' }
if (-not $OutBat) { $OutBat = Join-Path $ScriptDir 'Install-Alleaves.bat' }

# -LiteralPath, not -Path: a bracketed checkout dir is a wildcard. docs/BUILD-BAT.md#pack
if (-not (Test-Path -LiteralPath $Source)) { throw "Source not found: $Source" }

$srcBytes = [IO.File]::ReadAllBytes($Source)
$b64      = [Convert]::ToBase64String($srcBytes)
# 4000-char lines vs cmd's ~8191 variable ceiling: docs/BUILD-BAT.md#pack
$chunks   = [regex]::Matches($b64, '.{1,4000}') | ForEach-Object { $_.Value }
Write-Host "Source:  $Source ($($srcBytes.Length) bytes)"
Write-Host "Base64:  $($b64.Length) chars in $($chunks.Count) chunk line(s)"

$b64File = 'alleaves_b64.txt'
$psFile  = 'alleaves_setup.ps1'

$L = New-Object System.Collections.Generic.List[string]
$L.Add('@echo off')
$L.Add('setlocal enableextensions')
$L.Add('REM ===================================================================')
$L.Add('REM  Install-Alleaves.bat - GENERATED by build-bat.ps1. Do not edit by')
$L.Add('REM  hand; edit alleaves_setup.ps1 and rebuild.')
$L.Add('REM  Double-click = install.  "-Uninstall" = reverse.  "-DryRun" = test.')
$L.Add('REM  Exit codes and usage: README.md.  Design: docs/ in the repo.')
$L.Add('REM ===================================================================')
$L.Add('')
$L.Add('REM --- Single elevation owner: probe elevated-integrity SID, relaunch once.')
$L.Add('REM  docs/BUILD-BAT.md#elevation-probe - absolute path, BOTH SIDs, and abort')
$L.Add('REM  (never relaunch) when the probe cannot answer. All three prevent a fork bomb.')
$L.Add('set "WHOAMI=%SystemRoot%\System32\whoami.exe"')
$L.Add('if not exist "%WHOAMI%" goto :probefail')
$L.Add('"%WHOAMI%" /groups | findstr /c:"S-1-16-12288" /c:"S-1-16-16384" >nul 2>&1')
$L.Add('if not errorlevel 1 goto :elevated')
$L.Add('REM  Second probe = the fork guard: no S-1-16-* label at all means the PROBE is')
$L.Add('REM  broken, not that the token is unelevated. Abort instead of relaunching.')
$L.Add('"%WHOAMI%" /groups | findstr /c:"S-1-16-" >nul 2>&1')
$L.Add('if errorlevel 1 goto :probefail')
$L.Add('echo Requesting administrator elevation...')
$L.Add('REM  "exit /b %ERRORLEVEL%" below MUST stay OUTSIDE any ( ) block, and this')
$L.Add('REM  relaunch is INTERACTIVE-only. docs/BUILD-BAT.md#elevation-probe')
$L.Add('if "%~1"=="" (')
$L.Add('  powershell -NoProfile -Command "exit (Start-Process -FilePath ''%~f0'' -Verb RunAs -Wait -PassThru).ExitCode"')
$L.Add(') else (')
$L.Add('  powershell -NoProfile -Command "exit (Start-Process -FilePath ''%~f0'' -ArgumentList ''%*'' -Verb RunAs -Wait -PassThru).ExitCode"')
$L.Add(')')
$L.Add('exit /b %ERRORLEVEL%')
$L.Add('')
$L.Add(':probefail')
$L.Add('echo [FAIL] Cannot determine this token''s integrity level - refusing to relaunch.')
$L.Add('echo        %SystemRoot%\System32\whoami.exe did not report a mandatory-label SID.')
$L.Add('echo        Run Install-Alleaves.bat from cmd.exe or Explorer, not from a bash/MSYS')
$L.Add('echo        shell - relaunching on an unreadable probe forks without bound.')
$L.Add('exit /b 3')
$L.Add('')
$L.Add(':elevated')
$L.Add('')
$L.Add('REM --- Record requested mode so the .ps1 can refuse a dropped -Uninstall.')
$L.Add('set "ALLEAVES_REQUESTED_MODE=install"')
$L.Add('echo %*| find /i "-uninstall" >nul 2>&1 && set "ALLEAVES_REQUESTED_MODE=uninstall"')
$L.Add('echo Mode: %ALLEAVES_REQUESTED_MODE%')
$L.Add('')
$L.Add('REM --- Force 64-bit PowerShell (Sysnative when launched from a 32-bit shell).')
$L.Add('set "PS=%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe"')
$L.Add('if exist "%SystemRoot%\Sysnative\WindowsPowerShell\v1.0\powershell.exe" set "PS=%SystemRoot%\Sysnative\WindowsPowerShell\v1.0\powershell.exe"')
$L.Add('')
$L.Add("REM --- Transport base64 via a TEMP FILE (cmd env vars truncate at ~8191).")
$L.Add("if exist `"%TEMP%\$b64File`" del /f /q `"%TEMP%\$b64File`"")
$L.Add("if exist `"%TEMP%\$psFile`" del /f /q `"%TEMP%\$psFile`"")
# Redirection FIRST, command second: docs/BUILD-BAT.md#echo-redirection
foreach ($c in $chunks) {
    $L.Add(">>`"%TEMP%\$b64File`" echo $c")
}
$L.Add('')
$L.Add('REM --- Decode the base64 file back to the original .ps1 bytes.')
$L.Add("`"%PS%`" -NoProfile -Command `"[IO.File]::WriteAllBytes(`$env:TEMP+'\$psFile',[Convert]::FromBase64String([IO.File]::ReadAllText(`$env:TEMP+'\$b64File')))`"")
$L.Add("if not exist `"%TEMP%\$psFile`" (")
$L.Add('  echo FATAL: decode failed - PowerShell could not write the script.')
$L.Add("  del /f /q `"%TEMP%\$b64File`" >nul 2>&1")
$L.Add('  pause')
$L.Add('  REM 10, NOT 9 - launcher-only. docs/BUILD-BAT.md#decode-guard')
$L.Add('  exit /b 10')
$L.Add(')')
$L.Add('')
$L.Add('REM --- Run synchronously in this elevated console; propagate exit code.')
$L.Add('REM  QUOTE any -SkipPrograms regex containing cmd metacharacters (| ^ & < >),')
$L.Add('REM  e.g. -SkipPrograms "Chrome|NiceLabel". docs/BUILD-BAT.md#args')
$L.Add("`"%PS%`" -NoProfile -ExecutionPolicy Bypass -File `"%TEMP%\$psFile`" %*")
$L.Add('set "RC=%ERRORLEVEL%"')
$L.Add('')
$L.Add('REM --- Temp hygiene + surface result for RMM/monitoring.')
$L.Add("del /f /q `"%TEMP%\$psFile`" >nul 2>&1")
$L.Add("del /f /q `"%TEMP%\$b64File`" >nul 2>&1")
$L.Add('echo.')
$L.Add('echo Alleaves setup exit code: %RC%')
$L.Add('REM  Skip the pause for unattended/RMM runs: set ALLEAVES_NOPAUSE=1.')
$L.Add('if not defined ALLEAVES_NOPAUSE pause')
$L.Add('exit /b %RC%')

# ASCII with no BOM, CRLF: a BOM on line 1 breaks `@echo off`. docs/BUILD-BAT.md#pack
$content = ($L -join "`r`n") + "`r`n"
[IO.File]::WriteAllText($OutBat, $content, (New-Object System.Text.ASCIIEncoding))
Write-Host "Wrote:   $OutBat ($((Get-Item $OutBat).Length) bytes)"

# Self-verify from the WRITTEN .bat, never from $chunks: docs/BUILD-BAT.md#self-verify
$prefix  = ">>`"%TEMP%\$b64File`" echo "
$emitted = [IO.File]::ReadAllLines($OutBat) |
           Where-Object   { $_.StartsWith($prefix, [StringComparison]::Ordinal) } |
           ForEach-Object { $_.Substring($prefix.Length) }
$decoded = [byte[]]@()
try   { $decoded = [Convert]::FromBase64String(($emitted -join '')) }
catch { Write-Host "  decode of emitted lines FAILED: $($_.Exception.Message)" -ForegroundColor Red }
$srcHash = (Get-FileHash -LiteralPath $Source -Algorithm SHA256).Hash
$tmp = [IO.Path]::GetTempFileName()
[IO.File]::WriteAllBytes($tmp, $decoded)
$decHash = (Get-FileHash -Path $tmp -Algorithm SHA256).Hash
Remove-Item $tmp -Force -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "=== Self-verification ==="
Write-Host "  source bytes : $($srcBytes.Length)"
Write-Host "  decoded bytes: $($decoded.Length)"
Write-Host "  source SHA256: $srcHash"
Write-Host "  decode SHA256: $decHash"
if ($decoded.Length -eq $srcBytes.Length -and $decHash -eq $srcHash) {
    Write-Host "  RESULT: byte-length AND SHA256 identical - OK" -ForegroundColor Green
    exit 0
} else {
    Write-Host "  RESULT: MISMATCH - build is corrupt" -ForegroundColor Red
    # docs/BUILD-BAT.md#corrupt
    Move-Item -LiteralPath $OutBat -Destination "$OutBat.corrupt" -Force
    Write-Host "  moved aside: $OutBat.corrupt" -ForegroundColor Red
    exit 1
}
